baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AWS Modernization Workshop: DevSecOps with Atlassian & Snyk"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "true"
uglyurls = "true"
enableEmoji = true
googleAnalytics = "UA-69111857-1"

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "Jay Yeras"
  # Description of the site, will be used in meta information
  description = "AWS Modernization Workshop: DevSecOps with Atlassian & Snyk"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Snyk"
url = "https://snyk.io"
weight = 8

[[menu.shortcuts]]
name = "<i class='fas fa-cog fa-spin'></i> Snyk Patterns Library"
url = "https://solutions.snyk.io"
weight = 9

[[menu.shortcuts]]
name = "<i class='fas fa-shopping-cart'></i> Snyk on the AWS Marketplace"
url = "https://aws.amazon.com/marketplace/seller-profile?id=bb528b8d-079c-455e-95d4-e68438530f85"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-hands-helping'></i> Atlassian & Snyk Partnership"
url = "https://snyk.io/atlassian/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-hands-helping'></i> AWS & Snyk Partnership"
url = "https://aws.amazon.com/partners/find/partnerdetails/?n=Snyk&id=0010L00001kXlYOQA0"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-graduation-cap'></i> AWS Modernization Workshops"
url = "https://awsworkshop.io"
weight = 13

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> AWS Builders Library"
url = "https://aws.amazon.com/builders-library/"
weight = 19

[[menu.shortcuts]]
name = "<i class='far fa-lightbulb'></i> Modernization with AWS"
url = "https://aws.amazon.com/blogs/modernizing-with-aws/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Snyk Workshop"
url = "https://snyk.awsworkshop.io/"
weight = 21

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true